version: '3'

services:
  appwrite:
    image: appwrite/appwrite:latest
    ports:
      - "80:80"
    environment:
      - APPWRITE_PROJECT_NAME=My App
      - APPWRITE_EMAIL_ADDRESS=guna@example.com
      - APPWRITE_PASSWORD=mysecretpassword
    
      

  react:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_APPWRITE_ENDPOINT=http://appwrite:80/v1
    depends_on:
      - appwrite



version: '3'

services:
  appwrite:
    image: appwrite/appwrite
    ports:
      - 8000:80
    environment:
      - APPWRITE_PROJECT_NAME=demo
      - APPWRITE_ENDPOINT=http://localhost/v1
      - APPWRITE_API_KEY=password
      - APPWRITE_ADMIN_EMAIL=admin@example.com
      - APPWRITE_ADMIN_PASSWORD=password
    depends_on:
      - db

  db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=appwrite
    ports:
      - "27017:27017"

  react:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_APPWRITE_ENDPOINT=http://appwrite:80/v1
    depends_on:
      - appwrite
